services:

  controller:
    image: 'trinodb/trino'
    hostname: trino
    volumes:
      - ./etc/catalog:/etc/trino/catalog
      - ./etc/config.properties:/etc/trino/config.properties
      - ./etc/password-authenticator.properties:/etc/trino/password-authenticator.properties
      - ./etc/password.db:/etc/trino/password.db
      - ./etc/keystore.p12:/etc/trino/keystore.p12
    ports:
      - "8443:8443" 
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - trino_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - trino_network

  dagster:
    build:
      context: .
      dockerfile: Dockerfile_dagster
    container_name: dagster
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./dagster_project:/opt/dagster/app          # ваш код
      - ./dagster_home:/opt/dagster/dagster_home    # метаданные Dagster
    working_dir: /opt/dagster/app                   # ← запускаемся прямо в каталоге проекта
    command: >
      bash -c "pip install --no-cache -r requirements.txt &&
              dagster dev -p 3000 -h 0.0.0.0"      # аргумент-каталог убран
    ports:
      - '3000:3000'
  
networks:
  trino_network:
    driver: bridge


volumes:
  postgres-db-volume:
  airflow-logs:
