services:

  controller:
    image: 'trinodb/trino'
    hostname: trino
    volumes:
      - ./etc/catalog:/etc/trino/catalog
      - ./etc/config.properties:/etc/trino/config.properties
      - ./etc/password-authenticator.properties:/etc/trino/password-authenticator.properties
      - ./etc/password.db:/etc/trino/password.db
      - ./etc/keystore.p12:/etc/trino/keystore.p12
    ports:
      - "8443:8443" 
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - trino_network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - trino_network

  mybot:
    build:
      context: .
      dockerfile: Dockerfile.mybot     # Соберётся автоматически при up --build
    image: mybot:latest
    container_name: mybot
    restart: unless-stopped
    env_file:
      - .env                           # .env лежит рядом с compose и НЕ попадает в образ
    environment:
      # Лучше указывать сервис Trino по имени в сети compose
      TRINO_HOST: controller
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      PIP_NO_CACHE_DIR: "1"
    volumes:
      - ./mybot:/app/mybot:ro          # Код монтируется read-only
      - ./data:/app/data               # Данные/картинки и т.д.
    depends_on:
      - controller
    networks:
      - trino_network
  
networks:
  trino_network:
    driver: bridge


volumes:
  postgres-db-volume:
  airflow-logs:
