FROM python:3.11-slim

WORKDIR /app

# зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# код
COPY bot/ ./bot/
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENV PYTHONUNBUFFERED=1

# запуск: сначала префетч, потом бот
ENTRYPOINT ["./entrypoint.sh"]

CMD ["bash","-lc","python -m bot.prefetch && exec python -m bot.bot"]